name: flutter_bloc_skeleton
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.7
  go_router: ^14.8.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  dio_cache_interceptor: ^3.5.1
  path_provider: ^2.1.5
  dio_cache_interceptor_hive_store: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  gsheets: ^0.5.0
  firebase_push_notification_module:
    git:
      url: https://github.com/Aashish-Dahal/fcm_module.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
