name: flutter_bloc_skeleton
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  easy_localization: ^3.0.5
  go_router: ^13.2.2
  get_it: ^7.6.8
  shared_preferences: ^2.2.2
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  firebase_auth: ^4.19.0
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.2
  dio_cache_interceptor_hive_store: ^3.2.2
  firebase_core: ^2.28.0
  flutter_screenutil: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
