name: flutter_bloc_skeleton
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  go_router: ^14.2.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  firebase_auth: ^5.1.2
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.3
  dio_cache_interceptor_hive_store: ^3.2.2
  firebase_core: ^3.2.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dart_pre_commit: ^5.3.0
  git_hooks: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
