name: flutter_bloc_skeleton
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  go_router: ^14.6.2
  get_it: ^8.0.2
  shared_preferences: ^2.3.3
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  firebase_auth: ^5.3.4
  dio_cache_interceptor: ^3.5.1
  path_provider: ^2.1.5
  dio_cache_interceptor_hive_store: ^4.0.0
  firebase_core: ^3.8.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
