on:
  pull_request:
    branches:
      - main
      - staging
      - production

  push:
    branches:
      - main
      - staging
      - production
name: "Dart Format & build App"
jobs:
  build:
    name: Format & Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        run: echo "Running setup-java..." && exit 0
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
      - run: echo "Completed setup-java."

      - name: Setup Flutter
        run: echo "Running flutter setup..." && exit 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: stable
      - run: echo "Completed flutter setup."

      - name: Flutter Clean
        run: echo "Running flutter clean..." && exit 0
      - run: flutter clean
      - run: echo "Completed flutter clean."

      - name: Flutter Pub Get
        run: echo "Running flutter pub get..." && exit 0
      - run: flutter pub get
      - run: echo "Completed flutter pub get."

      - name: Flutter Analyze
        run: echo "Running flutter analyze..." && exit 0
      - run: flutter analyze --fatal-infos
      - run: echo "Completed flutter analyze."

      - name: Dart Format
        run: echo "Running dart format..." && exit 0
      - run: dart format . --set-exit-if-changed
      - run: echo "Completed dart format."

      - name: Dart Fix
        run: echo "Running dart fix --apply..." && exit 0
      - run: dart fix --apply
      - run: echo "Completed dart fix --apply."

      - name: Flutter Build APK
        run: echo "Running flutter build apk..." && exit 0
      - run: flutter build apk --split-per-abi
      - run: echo "Completed flutter build apk."

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v1.0.${{github.run_number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "This is a release build."
      - uses: actions/github-script@v6
        with:
          script: |
            const event = context.payload;
            if (event.pull_request) {
              github.rest.issues.createComment({
                issue_number: event.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else {
              github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: event.after,
                body: message
              });
      - run: echo "Completed adding comment to the PR or commit."
